name: Python 应用构建

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 安装 Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 代码检查 (flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
  pyinstaller-build:
    runs-on: windows-latest
    steps:
    - name: 生成可执行文件
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        spec: 'hello.py'
        upload_exe_with_name: 'hello_app'  # 已修正命名
        options: --onefile
